
export const API_URLS = {

    //new api

    dashboard_counter: `/api/v1/dashboard-api`,
    withdrawl_Request: `/api/v1/inr-payout-request-list`,
    withdrawl_approved: `/api/v1/inr-payout-request-approval`,
    withdrawl_reject: `/api/v1/inr-payout-request-rejection`,
    withdrawl_approved_list: `/api/v1/inr-payout-request-list-success`,
    withdrawl_reject_list: `/api/v1/inr-payout-request-list-failed`,
    withdrawl_pending_list: `/api/v1/inr-payout-request-list-pending-from-gateway`,
    user_list: `/api/v1/user-list`,
    update_user_status: `/api/v1//update-user-status`,
    wingo_result_api: `/api/v1/update-wingo-result`,
    add_fund: `/api/v1/add-fund-to-user`,
    get_fund_history: `/api/v1/fund-transfer-history`,
    get_aviator_report: `/api/v1/get-aviator-report`,
    get_trx_report: `/api/v1/get-trx-report`,
    get_wingo_report: `/api/v1/get-wingo-report`,
    user_permission: `/api/v1/change-user-permisson`,
    day_book_report: `/api/v1/day-book-report`,
    get_name_code: `/api/v1/get-sponsor-name`,
    Change_Password:`api/v1/change-user-password`,
    up_team:`api/v1/get-up-team`,
    down_team:`api/v1/get-downline-team`,
    welcome_bonus: `/api/v1/tget-wlcm-bonus-admin-data`,
    deposit_bonus_data: `/api/v1/tget-dpst-bonus-admin-data`,
    self_deposit_bonus_data: `/api/v1/tget-slf-dpst-bonus-admin-data`,
    roi_bonus_data: `/api/v1/tget-roi-bonus-admin-data`,
    daily_salary_bonus_data: `/api/v1/tget-daily-salary-bonus-admin-data`,
    bet_bonus_data: `/api/v1/tget-bet-income-bonus-admin-data`,
    level_bonus_data: `/api/v1/tget-level-income-bonus-admin-data`,
    //chart
    business_chart: `/api/v1/user-business-status-bar-chart`,
    registration_chart: `/api/v1/user-registration-status-bar-chart`,
    trx_chart: `/api/v1/user-trx-status-area-chart`,
    wingo_chart: `/api/v1/user-wingo-status-area-chart`,
    avaitor_chart: `/api/v1/user-aviator-status-area-chart`,
    bonus_set: `/api/v1/set-income-amount`,
    coupon: `/api/v1/get-admin-coupon-list`,
    add_coupon: `/api/v1/add-admin-coupon-list`,
    update_coupon_record: `/api/v1/update-admin-coupon-list?t_id=`,

    //close
    get_next_gameid_one_min: `/api/v1/get-bet-one-min-next-id`,
    get_all_player: `/api/v1/getAllPlayer`,
    player_registration: `/api/v1/addPlayer`,
    get_username_by_referralid: `/api/v1/getUsernameBy_refId`,
    get_user_data_by_user_id: `/api/v1/getPlayerDataById`,
    update_player_record: `/api/v1/updatePlayerRecord`,
    winzo_withdrawl: `/api/v1/view-winzo-withdrawl-request-report`,
    wingo_deposit: `/api/v1/view-wingo-main-wallet`,
    add_sub_admin: `/api/v1/addSubAdmin`,
    get_sub_admin_list: `/api/v1/getSubAdmin`,
    get_new_assigned_menu_list: `/api/v1/getAssignSubMenu`,
    get_downline_data_by_id: `/api/v1/downline-referral-data`,
    manually_winning_api: `/api/v1/manually-winning`,
    manually_update_percentage_api: `/api/v1/manually-update-percentage`,


}
